version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY}api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9000:80"
    depends_on:
      - mssql
    networks:
      - product-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-16.04
    environment:
      - SA_PASSWORD=PaSsWrd_11
      - ACCEPT_EULA=Y
    ports:
      - "5423:1433"
    networks:
      - product-network

networks:
  product-network:
    driver: bridge